#!/bin/sh

allTemps=`sensors | awk '/Core/ {print $3}' | sed "s/[^0-9.]*//g"`
cpuUsage=`top -bn 1 | awk '/^%Cpu/ {print int($2 + $4 + $6)}'`

maxTemp=0

for temp in $allTemps; do
  if [ "${temp%.*}" -gt ${maxTemp%.*} ]
  then
    maxTemp=$temp
  fi
done

echo "$cpuUsage% $maxTemp 糖"



